import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Figtree, Bruno_Ace } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-figtree",
  display: "swap",
});

const brunoAce = Bruno_Ace({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bruno-ace",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} ${brunoAce.variable} antialiased bg-[#090707]`}
      >
        {/* Background for all pages */}
        <div className="fixed -z-10 w-full h-full">
          <div className="absolute w-[1200px] h-[1200px] left-[calc(50%-600px+28px)] top-[-103px]">
            <Image
              src="/assets/image.png"
              alt="Masked Background"
              fill
              className="object-cover"
              priority
            />
          </div>
        </div>

        {/* Content container with relative positioning */}
        <div className="relative z-0">{children}</div>
      </body>
    </html>
  );
}
